### ISSUE TITLE
Very Slick!  Couple of notes

### ISSUE THREAD

**Issue by jhollist** [r4pi/r4pi.org#1]
@sellorm really nice write up and slick way to get R up and running the Pi.  Couple of notes.

- After editing the r4pi.list:  You indicate that they will need use ctrl-x and type yes.  May also want to indicate that they will need to hit enter when nano asks "File name to write:..."
- sudo apt upgrade:  might want to warn that it can take a bit of time, especially if the Pi has not been updated in a while.
- Might want to give an indication on how to start R if not using the `ln`.  I assume audience for this is newer users so might not be obvious.

Those were the only nits I had to pick.  It works great, I played around a bit and was able to install a few things from CRAN directly without any issue.

**Comment by sellorm** [comment]
Thanks for this Jeff, it was really helpful in pushing me to simplify the initial installation. There's just a single deb file to install now and that sets everything up for you.

Installation from there should be a breeze compared to what you tried. Check it out at https://r4pi.org if you get the chance.

Thanks again for testing this for me!

**Comment by jhollist** [comment]
@sellorm that sounds like a great change.  If I get some time this weekend I'll take a look.
