### ISSUE TITLE
Bad link to GH

### ISSUE THREAD

**Issue by eddelbuettel** [r4pi/r4pi.org#2]
The top-level navigation bar has a link to 'Edit on GitHub' that has https://github.com/r4pi/r4pi.org/edit/master/docs/index.md but link does not resolve. The repo url link in `mkdocs.yml` looks correct so the issue may be something else.

**Comment by matt-dray** [comment]
Ah, the edit links point to `/master/docs/` when it should be `/main/content/`.

**Comment by sellorm** [comment]
Thanks both! 

Since I'm not using "master" or the default "docs" folder I had to override the default GitHub repo links in mkdocs.yml.
