### ISSUE TITLE
failure on RPI3 (ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by RMHogervorst** [r4pi/r4pi.org#3]
I've finally gotten around to testing this project, and so I followed the steps in the README.

* curl http://debs.r4pi.org/r4pi.gpg.key | sudo apt-key add -
* sudo nano /etc/apt/sources.list.d/r4pi.list

```
### r4pi.org - please don't edit this file unless you understand what it does ###
deb http://debs.r4pi.org buster main
```

* sudo apt update

error: 
```
Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://debs.r4pi.org buster InRelease' doesn't support architecture 'arm64'
```

Is my pi only looking at Inrelease ?
Or is my pi of the wrong type? (rpi 3 B)

**Comment by sellorm** [comment]
Hi Roel,

r4pi is only for the official Raspberry Pi OS at the moment.

I will think about duplicating it all for Ubuntu in the future if there's enough interest though.

Cheers,
Mark

**Comment by RMHogervorst** [comment]
Ah, alright. Fair enough
