### ISSUE TITLE
Not an issue, question regarding Golem package

### ISSUE THREAD

**Issue by jayantsolanki** [r4pi/r4pi.org#7]
recently installed R using r4pi, thank you so much for providing this repo.  Couple of questions:

- How to choose an older version of R
- Some packages, such as Golem, are not present in https://pkgs.r4pi.org/aarch64/index.html, how to install those?

Thanks

-
Jay

**Comment by jayantsolanki** [comment]
Nevermind, found out the installation steps:
REPO="c('https://pkgs.r4pi.org/aarch64', 'http://cran.rstudio.com/')" 
sudo su - -c "R -e \"install.packages('golem', repos=$REPO)\""

Reference: https://www.r-bloggers.com/2022/09/setting-up-your-own-shiny-and-rstudio-server-on-a-raspberry-pi/

Anyways, any options for installing older R versions?

**Comment by sellorm** [comment]
Apologies for the epic delay on this @jayantsolanki !

We don't currently support older versions of R as it's a lot of work just to keep up with package builds for the latest release.

Perhaps we'll revisit this in the future though.

Thanks for your interest.
