### ISSUE TITLE
R-Release errors on RPi 5

### ISSUE THREAD

**Issue by mnr** [r4pi/r4pi.org#8]
This is on a Raspberry Pi 5. 

> cat /sys/firmware/devicetree/base/model;echo

Raspberry Pi 5 Model B Rev 1.0

> sudo apt install r4pi

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-release : Depends: libopenblas-base but it is not installable
             Depends: libtiff5 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by sellorm** [comment]
Apologies for the ridiculous delay @mnr!

Are you still having issues or should I close this now?

**Comment by mnr** [comment]
Let's close this issue. I'm running r4pi on a rpi 5 without problems. If something comes up, I'll file an updated issue

**Comment by sellorm** [comment]
Awesome, thanks Mark
