### ISSUE TITLE
Flextable Package Install error

### ISSUE THREAD

**Issue by dirtpan** [r4pi/r4pi.org#9]
Was wondering if anyone has gotten this error while trying to install the Flextable package:

> library("flextable")
Error: package or namespace load failed for ‘flextable’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/wgivens/R/aarch64-unknown-linux-gnu-library/4.3/httpuv/libs/httpuv.so':
  libuv.so.1: cannot open shared object file: No such file or directory

**Comment by sellorm** [comment]
Apologies for the epic delay @dirtpan. Is this still an issue for you?

**Comment by sellorm** [comment]
Closing
